Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Enabled: false