# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop', require: false, group: 'development'
gem 'rspec', '~>3.12.0', group: 'development'

gem 'uuidtools', '~>2.1.5'
gem 'mojinizer', '~>0.2.2'
gem 'nokogiri', '~>1.13.8'

gem 'sequel', '~>5.58.0'
gem 'pg', '~>1.4.2'
