module Goi
  module Model
    module Grammar

      class HydratedRule
        def initialize: (rule: Rule, examples: [Example]) -> void

        attr_reader rule: Rule
        attr_reader examples: [Example]
      end

      class Rule

        def initialize: (id: String id, title: Nihongo::StringJP title, meaning: String meaning, how_to_use: [String] how_to_use, ?jlpt_level: Integer? jlpt_level, row_num: Integer row_num, date_added: Date date_added, ?lesson_codes: [String] lesson_codes, ?tags: [String] tags) -> void

        attr_reader id: String

        attr_reader title: Nihongo::StringJP

        attr_reader meaning: String

        attr_reader how_to_use: [String]

        attr_reader jlpt_level: Integer?

        attr_reader row_num: Integer

        attr_reader date_added: Date

        attr_reader lesson_codes: [String]

        attr_reader tags: [String]
      end

      class Example
        def initialize: (id: String id, rule_id: String rule_id, text: Nihongo::StringJP text, meaning: [String] meaning, ?sort_rank: Integer? sort_rank, ?lesson_codes: [String] lesson_codes, ?tags: [String] tags) -> void

        attr_reader id: String

        attr_reader rule_id: String

        attr_reader text: Nihongo::StringJP

        attr_reader meaning: [String]

        attr_reader sort_rank: Integer?

        attr_reader lesson_codes: [String]

        attr_reader tags: [String]
      end

    end
  end
end
