module Goi
  module Model
    class Kanji
      UUID5_NAMESPACE: String

      def self.create_id: (character: String character) -> String

      def initialize: (
          id: String id,
          character: String character,
          unicode_code_point: (Integer|String) unicode_code_point,
          meanings: [String] meanings,
          on_readings: [String] on_readings,
          kun_readings: [String] kun_readings,
          nanori_readings: [String] nanori_readings,
          stroke_count: Integer stroke_count,
          jlpt_level: Integer? jlpt_level,
          grade_level: Integer? grade,
          frequency_ranking: Integer? frequency_ranking
        ) -> void

      attr_reader id: String

      attr_reader character: String

      attr_reader meanings: [String]

      attr_reader on_readings: [String]

      attr_reader kun_readings: [String]

      attr_reader nanori_readings: [String]

      attr_reader stroke_count: Integer

      attr_reader jlpt_level: Integer?

      attr_reader grade_level: Integer?

      attr_reader frequency_ranking: Integer?

      def unicode_code_point_hex: () -> String

      def unicode_code_point_int: () -> Integer
    end
  end
end
