module Goi
  module Pipeline
    module Vocabulary
      module Transformer
        class Base < Goi::Pipeline::Core::Transformer[[Goi::Model::Vocabulary::Linkages]]
        end
      end
    end
  end
end

