module Goi
  module Importer

    class GoogleSheetImporter < BaseImporter[Pathname]

      type field_data = { linkage_field: Symbol, key: String }

      PREFERRED_SPELLING_FIELD_DATA: field_data
      PHONETIC_SPELLING_FIELD_DATA: field_data
      ALT_PHONETIC_SPELLING_FIELD_DATA: field_data
      KANJI_SPELLING_FIELD_DATA: field_data

      attr_reader vocabulary_parser: VocabularyParser
      attr_reader definition_parser: DefinitionParser
      attr_reader spelling_parser: SpellingParser

      def import: (Pathname file_path) -> [Model::Vocabulary::Linkages]

      private

      def parse_rows: (rows: [Hash[String, String]] rows) -> [Model::Vocabulary::Linkages]

      def parse_row: (row: Hash[String, String] row) -> Model::Vocabulary::Linkages

      def parse_vocabulary: (row: Hash[String, String] row, vocabulary_id: String vocabulary_id) -> Model::Vocabulary::Vocabulary

      def parse_definition: (row: Hash[String, String] row, vocabulary_id: String vocabulary_id) -> Model::Vocabulary::Definition

      def parse_spelling: (row: Hash[String, String] row, field_data: field_data field_data, required: bool required, vocabulary_id: String vocabulary_id) -> Model::Vocabulary::Spelling

    end

    class VocabularyParser

      def parse_row: (row: Hash[String, String] row) -> Model::Vocabulary::Vocabulary

      private

      def array_parse: (String?) -> [String]

    end

    class DefinitionParser

      def parse_row: (row: Hash[String, String] row, vocabulary_id: String vocabulary_id) -> Model::Vocabulary::Definition

    end

    class SpellingParser

      CODE_MAP: Hash[Symbol, String]

      def parse_row: (row: Hash[String, String] row, field_data: GoogleSheetImporter::field_data field_data, ?required: bool required, vocabulary_id: String vocabulary_id) -> Model::Vocabulary::Spelling

      private

      def infer_kind_code: (String value) -> String

    end

  end
end
