module Goi
  module Exporter
    class IOExporter < BaseExporter[Goi::Application::Config]
      def initialize: (config: Goi::Application::Config) -> void

      attr_reader io: IO

      def export: (linkages: [Model::Vocabulary::Linkages] linkages) -> void
    end
  end
end
