module Goi
  module Exporter
    class IOExporter < BaseExporter[String]
      def initialize: (?io: IO io) -> void

      attr_reader io: IO

      def export: (linkages: [Model::Vocabulary::Linkages] linkages) -> void
    end
  end
end
