module Goi
  module Exporter
    class SqlFileExporter < BaseExporter[void]

      def initialize: () -> void

      attr_reader db: untyped

      attr_reader io: IO

      attr_reader mode: Symbol

      def export: (linkages: [Model::Vocabulary::Linkages] linkages) -> untyped

    end
  end
end
