module Goi
  module Exporter
    module Core
      class BaseExporter
        def initialize: (config: Goi::Exporter::Core::Config) -> void

        attr_reader config: Config

        def export: (linkages: [Model::Vocabulary::Linkages] linkages) -> void

        private

        def config_out_open: () { (IO) -> void } -> void
      end
    end
  end
end
