module Goi
  module Pipeline
    module Vocabulary
      module Library

        type db_config = {database: String, user: String, password: String, host: String}

        def self.default: (db_config: db_config db_config, infile_pathname: Pathname infile_pathname, output_dir_pathname: Pathname? output_dir_pathname) -> untyped

        private

        OUTFILE_NAMES: Hash[Symbol, String]

        def self.output_file: (output_dir_pathname: Pathname? output_dir_pathname, outfile_key: Symbol outfile_key) -> Pathname?

      end
    end
  end
end
